### ISSUE TITLE
symbol not found in flat namespace '_rust_crypto_util_fixed_time_eq_asm'

### ISSUE THREAD

**Issue by bhaagiKenpachi** [ZenGo-X/multi-party-ecdsa#187]
After cargo build, on running ./run.sh or run20.sh script, getting below error.

keygen part
key gen for client 1 out of 3
dyld[46200]: symbol not found in flat namespace '_rust_crypto_util_fixed_time_eq_asm'
./demo/run.sh: line 21: 46200 Abort trap: 6           ./target/release/examples/gg18_keygen_client http://127.0.0.1:8001 keys"$i".store
key gen for client 2 out of 3
dyld[46202]: symbol not found in flat namespace '_rust_crypto_util_fixed_time_eq_asm'
./demo/run.sh: line 21: 46202 Abort trap: 6           ./target/release/examples/gg18_keygen_client http://127.0.0.1:8001 keys"$i".store
key gen for client 3 out of 3
dyld[46204]: symbol not found in flat namespace '_rust_crypto_util_fixed_time_eq_asm'
./demo/run.sh: line 21: 46204 Abort trap: 6           ./target/release/examples/gg18_keygen_client http://127.0.0.1:8001 keys"$i".store
sign
signing for client 1 out of 2
thread 'main' panicked at 'Unable to load keys, did you run keygen first? : Os { code: 2, kind: NotFound, message: "No such file or directory" }', examples/gg18_sign_client.rs:47:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
signing for client 2 out of 2
thread 'main' panicked at 'Unable to load keys, did you run keygen first? : Os { code: 2, kind: NotFound, message: "No such file or directory" }', examples/gg18_sign_client.rs:47:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by leontiad** [comment]
Hi, I cannot reproduce that locally

**Comment by bhaagiKenpachi** [comment]
@leontiad  Can you please provide OS details , requirements , packages to be installed , steps to run?

**Comment by leontiad** [comment]
Other than rust there shouldn't be other requirement to run that. What are you getting after running:

cargo +nightly build --examples --release
cd target/release/example
./gg20_sm_manager

./gg20_keygen -t 1 -n 3 -i 1 --output local-share1.json
./gg20_keygen -t 1 -n 3 -i 2 --output local-share2.json
./gg20_keygen -t 1 -n 3 -i 3 --output local-share3.json


./gg20_signing -p 1,2 -d "test" -l local-share1.json
./gg20_signing -p 1,2 -d "test" -l local-share2.json
